name: Deploy to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
      
      - name: Deploy static site to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --cache-control 'max-age=86400'
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          SOURCE_DIR: .
          DEST_DIR: ''
          AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
          EXCLUDE_PATTERN: '.git/* .github/* server.py README.md .gitignore resume/*'
      
      - name: Set shorter cache for HTML files
        run: |
          aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/index.html s3://${{ secrets.S3_BUCKET_NAME }}/index.html \
            --metadata-directive REPLACE \
            --cache-control "max-age=3600"
      
      - name: Check if CloudFront distribution ID exists
        id: check-cloudfront
        run: |
          if [ -n "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
            echo "has_distribution=true" >> $GITHUB_OUTPUT
          else
            echo "has_distribution=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Invalidate CloudFront distribution
        if: steps.check-cloudfront.outputs.has_distribution == 'true'
        run: |
          # Create CloudFront invalidation to ensure changes are immediately visible
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
